<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link href="css/vendor/bootstrap-3.3.7.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container ">
            <div class="page-header">
                Aplicación de administración
            </div>
            <nav class="navbar navbar-default" role="navigation">
                <!-- El logotipo y el icono que despliega el menú se agrupan
                     para mostrarlos mejor en los dispositivos móviles -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse"
                            data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Desplegar navegación</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/home">Home</a>
                </div>
                <!-- Agrupar los enlaces de navegación, los formularios y cualquier
                     otro elemento que se pueda ocultar al minimizar la barra -->
                <div class="collapse navbar-collapse navbar-ex1-collapse">
                    <ul class="nav navbar-nav">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Eventos <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="/createEvent">Crear evento</a></li>
                            </ul>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                Acciones hacia la aplicación<b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Configurar mi usuario</a></li>
                                <li class="divider"></li>
                                <li class="text-center">
                                    <form method="get" action="/logout">
                                        <button type="submit" class="btn btn-danger">Cerrar la sesión</button>
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
            <!--aqui va el codigo de la pagina-->
            Home!
        </div>
        <script src="js/vendor/jquery-3.2.1.min.js"></script>
        <script src="js/vendor/bootstrap-3.3.7.min.js"></script>
        <script src="js/home.js"></script>
    </body>
</html>

