<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <link href="css/vendor/bootstrap-3.3.7.min.css" rel="stylesheet">
        <meta name="viewport" content="width=device-width, initial-scale=1">
    </head>
    <body>
        <div class="container">
            <div class="row">
                <div class="col-xs-1 col-sm-3 col-md-3 col-lg-4"></div>
                <div class="col-xs-10 col-sm-8 col-md-4 col-lg-4">
                    <div class="page-header">
                        <h3>Iniciar sesión</h3>
                    </div>
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <form method="post" action="/login">
                                <div class="form-group">
                                    <label for="user">Usuario</label>
                                    <input type="text" value="<?= $user ?>" placeholder="Usuario" id="user" name="user" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <label for="pass">Contraseña</label>
                                    <input type="password" value="<?= $pass ?>" placeholder="Contraseña" id="pass" name="pass" class="form-control" />
                                </div>
                                <div class="form-group">
                                    <input type="submit" class="btn btn-primary btn-block" value="Iniciar sesión">
                                </div>
                            </form>
                        </div>
                        <div class="panel-footer text-center">
                            <?php
                            if (!empty($user)) {
                                ?>
                                <div class="alert alert-danger">
                                    No se autorizó el acceso a la aplicación
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
                <div class="col-xs-1 col-sm-3 col-md-4 col-lg-4"></div>
            </div>
        </div>
        <script src="js/vendor/jquery-3.2.1.min.js"></script>
        <script src="js/vendor/bootstrap-3.3.7.min.js"></script>
        <script src="js/login.js"></script>
    </body>
</html>
