INSERT INTO CIUDAD VALUES (1, 'BOGOTA'), (2, 'MEDELLIN'); 
INSERT INTO INFO VALUES (1, '2.4', '2017/10/09', 'ULTIMA VERSION'), (2, '1.0', '2017/10/05', 'PRIMERA VERSION');
INSERT INTO FACULTAD VALUES (1, 'INGENIERIA Y CIENCIAS BASICAS'), (2, 'CIENCIAS SOCIALES'), (3, 'CIENCIAS SOCIALES'), (4, 'CIENCIAS ADMINISTRATIVAS, ECONOMICAS Y CONTABLES'), (5, 'MERCADEO COMUNICACION Y ARTES');


INSERT INTO EVENTO (1, 'ASESORIA MATEMATICAS', NOW(), 'X.JPG', 'TEMAS DE REPASO: ALGEBRA BASICA, TRIGONOMETRIA', 'DESCRIPCION X', 'INGENIERIA', 1, 'SALON 3', 15, 1,5, 1, 50);
INSERT INTO LOG VALUES (1, 1, SELECT NOMBRE_USUARIO FROM USUARIO WHERE ID_USUARIO = 1, '2017/10/9', 'LOGIN', 'INGRESO A APP' );